/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AuthBody model module.
 * @module model/AuthBody
 * @version 1.6
 */
export class AuthBody {
  /**
   * Constructs a new <code>AuthBody</code>.
   * Authentication model
   * @alias module:model/AuthBody
   * @class
   * @param email {String} This is the email of the user in GetAccept
   * @param password {String} This is the password of the user in GetAccept
   */
  constructor(email, password) {
    this.email = email;
    this.password = password;
  }

  /**
   * Constructs a <code>AuthBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AuthBody} obj Optional instance to populate.
   * @return {module:model/AuthBody} The populated <code>AuthBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AuthBody();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('entity_id'))
        obj.entityId = ApiClient.convertToType(data['entity_id'], 'String');
      if (data.hasOwnProperty('client_id'))
        obj.clientId = ApiClient.convertToType(data['client_id'], 'String');
    }
    return obj;
  }
}

/**
 * This is the email of the user in GetAccept
 * @member {String} email
 */
AuthBody.prototype.email = undefined;

/**
 * This is the password of the user in GetAccept
 * @member {String} password
 */
AuthBody.prototype.password = undefined;

/**
 * This specifies what entity to select if multiple entities are available for a user. If no value is specified the default entity will be selected.
 * @member {String} entityId
 * @default ''
 */
AuthBody.prototype.entityId = '';

/**
 * The client id of your app if you received one from our API team
 * @member {String} clientId
 * @default ''
 */
AuthBody.prototype.clientId = '';

