/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Contact} from './Contact';

/**
 * The Contacts model module.
 * @module model/Contacts
 * @version 1.6
 */
export class Contacts {
  /**
   * Constructs a new <code>Contacts</code>.
   * Contact list
   * @alias module:model/Contacts
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Contacts</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Contacts} obj Optional instance to populate.
   * @return {module:model/Contacts} The populated <code>Contacts</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Contacts();
      if (data.hasOwnProperty('contacts'))
        obj.contacts = ApiClient.convertToType(data['contacts'], [Contact]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Contact>} contacts
 */
Contacts.prototype.contacts = undefined;

