/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DocumentsRecipients model module.
 * @module model/DocumentsRecipients
 * @version 1.6
 */
export class DocumentsRecipients {
  /**
   * Constructs a new <code>DocumentsRecipients</code>.
   * @alias module:model/DocumentsRecipients
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DocumentsRecipients</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentsRecipients} obj Optional instance to populate.
   * @return {module:model/DocumentsRecipients} The populated <code>DocumentsRecipients</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DocumentsRecipients();
      if (data.hasOwnProperty('first_name'))
        obj.firstName = ApiClient.convertToType(data['first_name'], 'String');
      if (data.hasOwnProperty('last_name'))
        obj.lastName = ApiClient.convertToType(data['last_name'], 'String');
      if (data.hasOwnProperty('role'))
        obj.role = ApiClient.convertToType(data['role'], 'String');
      if (data.hasOwnProperty('role_name'))
        obj.roleName = ApiClient.convertToType(data['role_name'], 'String');
      if (data.hasOwnProperty('verify_qna_sign'))
        obj.verifyQnaSign = ApiClient.convertToType(data['verify_qna_sign'], 'Boolean');
      if (data.hasOwnProperty('verify_qna_question'))
        obj.verifyQnaQuestion = ApiClient.convertToType(data['verify_qna_question'], 'String');
      if (data.hasOwnProperty('verify_qna'))
        obj.verifyQna = ApiClient.convertToType(data['verify_qna'], 'Boolean');
      if (data.hasOwnProperty('company_name'))
        obj.companyName = ApiClient.convertToType(data['company_name'], 'String');
      if (data.hasOwnProperty('company_number'))
        obj.companyNumber = ApiClient.convertToType(data['company_number'], 'String');
      if (data.hasOwnProperty('verify_qna_open'))
        obj.verifyQnaOpen = ApiClient.convertToType(data['verify_qna_open'], 'Boolean');
      if (data.hasOwnProperty('verify_qna_answer'))
        obj.verifyQnaAnswer = ApiClient.convertToType(data['verify_qna_answer'], 'String');
      if (data.hasOwnProperty('verify_sms_sign'))
        obj.verifySmsSign = ApiClient.convertToType(data['verify_sms_sign'], 'Boolean');
      if (data.hasOwnProperty('verify_eid_type'))
        obj.verifyEidType = ApiClient.convertToType(data['verify_eid_type'], 'String');
      if (data.hasOwnProperty('note'))
        obj.note = ApiClient.convertToType(data['note'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('mobile'))
        obj.mobile = ApiClient.convertToType(data['mobile'], 'String');
      if (data.hasOwnProperty('verify_sms'))
        obj.verifySms = ApiClient.convertToType(data['verify_sms'], 'Boolean');
      if (data.hasOwnProperty('verify_sms_open'))
        obj.verifySmsOpen = ApiClient.convertToType(data['verify_sms_open'], 'Boolean');
      if (data.hasOwnProperty('order_num'))
        obj.orderNum = ApiClient.convertToType(data['order_num'], 'Number');
      if (data.hasOwnProperty('verify_eid'))
        obj.verifyEid = ApiClient.convertToType(data['verify_eid'], 'Boolean');
    }
    return obj;
  }
}

/**
 * Recipient first name
 * @member {String} firstName
 */
DocumentsRecipients.prototype.firstName = undefined;

/**
 * Last name of recipient
 * @member {String} lastName
 */
DocumentsRecipients.prototype.lastName = undefined;

/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
DocumentsRecipients.RoleEnum = {
  /**
   * value: "signer"
   * @const
   */
  signer: "signer",

  /**
   * value: "approver"
   * @const
   */
  approver: "approver",

  /**
   * value: "cc"
   * @const
   */
  cc: "cc"
};
/**
 * The kind of recipient in the document
 * @member {module:model/DocumentsRecipients.RoleEnum} role
 */
DocumentsRecipients.prototype.role = undefined;

/**
 * The name of the role in a template
 * @member {String} roleName
 */
DocumentsRecipients.prototype.roleName = undefined;

/**
 * Should a question be asked before signing
 * @member {Boolean} verifyQnaSign
 */
DocumentsRecipients.prototype.verifyQnaSign = undefined;

/**
 * Question to ask for verification
 * @member {String} verifyQnaQuestion
 */
DocumentsRecipients.prototype.verifyQnaQuestion = undefined;

/**
 * Should a question be asked
 * @member {Boolean} verifyQna
 */
DocumentsRecipients.prototype.verifyQna = undefined;

/**
 * Company name of the recipient
 * @member {String} companyName
 */
DocumentsRecipients.prototype.companyName = undefined;

/**
 * Company number of the recipient
 * @member {String} companyNumber
 */
DocumentsRecipients.prototype.companyNumber = undefined;

/**
 * Should question be asked before opening document
 * @member {Boolean} verifyQnaOpen
 */
DocumentsRecipients.prototype.verifyQnaOpen = undefined;

/**
 * The answer to question
 * @member {String} verifyQnaAnswer
 */
DocumentsRecipients.prototype.verifyQnaAnswer = undefined;

/**
 * Should a SMS verify the recipient before signing
 * @member {Boolean} verifySmsSign
 */
DocumentsRecipients.prototype.verifySmsSign = undefined;

/**
 * EID type to be used for personal verification
 * @member {String} verifyEidType
 */
DocumentsRecipients.prototype.verifyEidType = undefined;

/**
 * Additional note for a recipient
 * @member {String} note
 */
DocumentsRecipients.prototype.note = undefined;

/**
 * Email address of the recipient
 * @member {String} email
 */
DocumentsRecipients.prototype.email = undefined;

/**
 * Mobile phone in international format
 * @member {String} mobile
 */
DocumentsRecipients.prototype.mobile = undefined;

/**
 * Verify recipient by SMS
 * @member {Boolean} verifySms
 */
DocumentsRecipients.prototype.verifySms = undefined;

/**
 * Verify SMS on open
 * @member {Boolean} verifySmsOpen
 */
DocumentsRecipients.prototype.verifySmsOpen = undefined;

/**
 * If signing order is enabled
 * @member {Number} orderNum
 */
DocumentsRecipients.prototype.orderNum = undefined;

/**
 * Verify using EID
 * @member {Boolean} verifyEid
 */
DocumentsRecipients.prototype.verifyEid = undefined;

