/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DocumentIdSealBody model module.
 * @module model/DocumentIdSealBody
 * @version 1.6
 */
export class DocumentIdSealBody {
  /**
   * Constructs a new <code>DocumentIdSealBody</code>.
   * @alias module:model/DocumentIdSealBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DocumentIdSealBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentIdSealBody} obj Optional instance to populate.
   * @return {module:model/DocumentIdSealBody} The populated <code>DocumentIdSealBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DocumentIdSealBody();
      if (data.hasOwnProperty('sender_id'))
        obj.senderId = ApiClient.convertToType(data['sender_id'], 'String');
      if (data.hasOwnProperty('sender_email'))
        obj.senderEmail = ApiClient.convertToType(data['sender_email'], 'String');
    }
    return obj;
  }
}

/**
 * Use this to specify the sender user/owner by id to be used for self-signing the document.
 * @member {String} senderId
 */
DocumentIdSealBody.prototype.senderId = undefined;

/**
 * Use this to specify the sender user/owner by email address to be used for self-signing the document.
 * @member {String} senderEmail
 */
DocumentIdSealBody.prototype.senderEmail = undefined;

