/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DocumentsCustomFields model module.
 * @module model/DocumentsCustomFields
 * @version 1.6
 */
export class DocumentsCustomFields {
  /**
   * Constructs a new <code>DocumentsCustomFields</code>.
   * @alias module:model/DocumentsCustomFields
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DocumentsCustomFields</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DocumentsCustomFields} obj Optional instance to populate.
   * @return {module:model/DocumentsCustomFields} The populated <code>DocumentsCustomFields</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DocumentsCustomFields();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * ID of custom template field
 * @member {String} id
 */
DocumentsCustomFields.prototype.id = undefined;

/**
 * Name of custom template field
 * @member {String} name
 */
DocumentsCustomFields.prototype.name = undefined;

/**
 * Value of custom template field
 * @member {String} value
 */
DocumentsCustomFields.prototype.value = undefined;

