/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The EventsRejectedBody model module.
 * @module model/EventsRejectedBody
 * @version 1.6
 */
export class EventsRejectedBody {
  /**
   * Constructs a new <code>EventsRejectedBody</code>.
   * @alias module:model/EventsRejectedBody
   * @class
   * @param event {String} Event trigger
   * @param targetUrl {String} The URL to post payload to on event
   */
  constructor(event, targetUrl) {
    this.event = event;
    this.targetUrl = targetUrl;
  }

  /**
   * Constructs a <code>EventsRejectedBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventsRejectedBody} obj Optional instance to populate.
   * @return {module:model/EventsRejectedBody} The populated <code>EventsRejectedBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EventsRejectedBody();
      if (data.hasOwnProperty('event'))
        obj.event = ApiClient.convertToType(data['event'], 'String');
      if (data.hasOwnProperty('target_url'))
        obj.targetUrl = ApiClient.convertToType(data['target_url'], 'String');
      if (data.hasOwnProperty('host'))
        obj.host = ApiClient.convertToType(data['host'], 'String');
      if (data.hasOwnProperty('payload'))
        obj.payload = ApiClient.convertToType(data['payload'], 'String');
      if (data.hasOwnProperty('global'))
        obj.global = ApiClient.convertToType(data['global'], 'Boolean');
      if (data.hasOwnProperty('notification_email'))
        obj.notificationEmail = ApiClient.convertToType(data['notification_email'], 'String');
    }
    return obj;
  }
}

/**
 * Event trigger
 * @member {String} event
 * @default 'document.rejected'
 */
EventsRejectedBody.prototype.event = 'document.rejected';

/**
 * The URL to post payload to on event
 * @member {String} targetUrl
 */
EventsRejectedBody.prototype.targetUrl = undefined;

/**
 * The host name to send the post to
 * @member {String} host
 */
EventsRejectedBody.prototype.host = undefined;

/**
 * Additional payload data to post
 * @member {String} payload
 */
EventsRejectedBody.prototype.payload = undefined;

/**
 * If the webhook should catch events for all entity users.
 * @member {Boolean} global
 * @default true
 */
EventsRejectedBody.prototype.global = true;

/**
 * If the event fails, send a notification to this email instead of the sender
 * @member {String} notificationEmail
 */
EventsRejectedBody.prototype.notificationEmail = undefined;

