/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Field} from './Field';

/**
 * The Fields model module.
 * @module model/Fields
 * @version 1.6
 */
export class Fields {
  /**
   * Constructs a new <code>Fields</code>.
   * Field list
   * @alias module:model/Fields
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Fields</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Fields} obj Optional instance to populate.
   * @return {module:model/Fields} The populated <code>Fields</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Fields();
      if (data.hasOwnProperty('fields'))
        obj.fields = ApiClient.convertToType(data['fields'], [Field]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/Field>} fields
 */
Fields.prototype.fields = undefined;

