/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse20011Attachments model module.
 * @module model/InlineResponse20011Attachments
 * @version 1.6
 */
export class InlineResponse20011Attachments {
  /**
   * Constructs a new <code>InlineResponse20011Attachments</code>.
   * @alias module:model/InlineResponse20011Attachments
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse20011Attachments</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20011Attachments} obj Optional instance to populate.
   * @return {module:model/InlineResponse20011Attachments} The populated <code>InlineResponse20011Attachments</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20011Attachments();
      if (data.hasOwnProperty('attachment_id'))
        obj.attachmentId = ApiClient.convertToType(data['attachment_id'], 'String');
      if (data.hasOwnProperty('attachment_type'))
        obj.attachmentType = ApiClient.convertToType(data['attachment_type'], 'String');
      if (data.hasOwnProperty('attachment_title'))
        obj.attachmentTitle = ApiClient.convertToType(data['attachment_title'], 'String');
      if (data.hasOwnProperty('attachment_url'))
        obj.attachmentUrl = ApiClient.convertToType(data['attachment_url'], 'String');
      if (data.hasOwnProperty('published'))
        obj.published = ApiClient.convertToType(data['published'], 'Boolean');
      if (data.hasOwnProperty('library'))
        obj.library = ApiClient.convertToType(data['library'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} attachmentId
 */
InlineResponse20011Attachments.prototype.attachmentId = undefined;

/**
 * @member {String} attachmentType
 */
InlineResponse20011Attachments.prototype.attachmentType = undefined;

/**
 * @member {String} attachmentTitle
 */
InlineResponse20011Attachments.prototype.attachmentTitle = undefined;

/**
 * @member {String} attachmentUrl
 */
InlineResponse20011Attachments.prototype.attachmentUrl = undefined;

/**
 * @member {Boolean} published
 */
InlineResponse20011Attachments.prototype.published = undefined;

/**
 * @member {Boolean} library
 */
InlineResponse20011Attachments.prototype.library = undefined;

