/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse2002Templates model module.
 * @module model/InlineResponse2002Templates
 * @version 1.6
 */
export class InlineResponse2002Templates {
  /**
   * Constructs a new <code>InlineResponse2002Templates</code>.
   * @alias module:model/InlineResponse2002Templates
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2002Templates</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2002Templates} obj Optional instance to populate.
   * @return {module:model/InlineResponse2002Templates} The populated <code>InlineResponse2002Templates</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2002Templates();
      if (data.hasOwnProperty('is_private'))
        obj.isPrivate = ApiClient.convertToType(data['is_private'], 'Boolean');
      if (data.hasOwnProperty('role_count'))
        obj.roleCount = ApiClient.convertToType(data['role_count'], 'Number');
      if (data.hasOwnProperty('thumb_url'))
        obj.thumbUrl = ApiClient.convertToType(data['thumb_url'], 'String');
      if (data.hasOwnProperty('video_id'))
        obj.videoId = ApiClient.convertToType(data['video_id'], 'String');
      if (data.hasOwnProperty('video_thumb_url'))
        obj.videoThumbUrl = ApiClient.convertToType(data['video_thumb_url'], 'String');
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], 'String');
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('external_editor_type'))
        obj.externalEditorType = ApiClient.convertToType(data['external_editor_type'], 'String');
      if (data.hasOwnProperty('is_editable'))
        obj.isEditable = ApiClient.convertToType(data['is_editable'], 'Boolean');
      if (data.hasOwnProperty('tags'))
        obj.tags = ApiClient.convertToType(data['tags'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('page_count'))
        obj.pageCount = ApiClient.convertToType(data['page_count'], 'Number');
      if (data.hasOwnProperty('field_count'))
        obj.fieldCount = ApiClient.convertToType(data['field_count'], 'Number');
      if (data.hasOwnProperty('sender_name'))
        obj.senderName = ApiClient.convertToType(data['sender_name'], 'String');
      if (data.hasOwnProperty('sender_thumb_url'))
        obj.senderThumbUrl = ApiClient.convertToType(data['sender_thumb_url'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Boolean} isPrivate
 */
InlineResponse2002Templates.prototype.isPrivate = undefined;

/**
 * @member {Number} roleCount
 */
InlineResponse2002Templates.prototype.roleCount = undefined;

/**
 * @member {String} thumbUrl
 */
InlineResponse2002Templates.prototype.thumbUrl = undefined;

/**
 * @member {String} videoId
 */
InlineResponse2002Templates.prototype.videoId = undefined;

/**
 * @member {String} videoThumbUrl
 */
InlineResponse2002Templates.prototype.videoThumbUrl = undefined;

/**
 * @member {String} userId
 */
InlineResponse2002Templates.prototype.userId = undefined;

/**
 * @member {String} createdAt
 */
InlineResponse2002Templates.prototype.createdAt = undefined;

/**
 * @member {String} name
 */
InlineResponse2002Templates.prototype.name = undefined;

/**
 * @member {String} externalEditorType
 */
InlineResponse2002Templates.prototype.externalEditorType = undefined;

/**
 * @member {Boolean} isEditable
 */
InlineResponse2002Templates.prototype.isEditable = undefined;

/**
 * @member {String} tags
 */
InlineResponse2002Templates.prototype.tags = undefined;

/**
 * @member {String} id
 */
InlineResponse2002Templates.prototype.id = undefined;

/**
 * @member {String} type
 */
InlineResponse2002Templates.prototype.type = undefined;

/**
 * @member {Number} pageCount
 */
InlineResponse2002Templates.prototype.pageCount = undefined;

/**
 * @member {Number} fieldCount
 */
InlineResponse2002Templates.prototype.fieldCount = undefined;

/**
 * @member {String} senderName
 */
InlineResponse2002Templates.prototype.senderName = undefined;

/**
 * @member {String} senderThumbUrl
 */
InlineResponse2002Templates.prototype.senderThumbUrl = undefined;

