/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse2008 model module.
 * @module model/InlineResponse2008
 * @version 1.6
 */
export class InlineResponse2008 {
  /**
   * Constructs a new <code>InlineResponse2008</code>.
   * @alias module:model/InlineResponse2008
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2008</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2008} obj Optional instance to populate.
   * @return {module:model/InlineResponse2008} The populated <code>InlineResponse2008</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2008();
      if (data.hasOwnProperty('file_id'))
        obj.fileId = ApiClient.convertToType(data['file_id'], 'String');
      if (data.hasOwnProperty('file_status'))
        obj.fileStatus = ApiClient.convertToType(data['file_status'], 'String');
    }
    return obj;
  }
}

/**
 * ID of the uploaded file to be used in file_ids when creating a document
 * @member {String} fileId
 */
InlineResponse2008.prototype.fileId = undefined;

/**
 * Status of the uploaded file
 * @member {String} fileStatus
 */
InlineResponse2008.prototype.fileStatus = undefined;

