/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse20010 model module.
 * @module model/InlineResponse20010
 * @version 1.6
 */
export class InlineResponse20010 {
  /**
   * Constructs a new <code>InlineResponse20010</code>.
   * @alias module:model/InlineResponse20010
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse20010</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20010} obj Optional instance to populate.
   * @return {module:model/InlineResponse20010} The populated <code>InlineResponse20010</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse20010();
      if (data.hasOwnProperty('video_id'))
        obj.videoId = ApiClient.convertToType(data['video_id'], 'String');
      if (data.hasOwnProperty('filename'))
        obj.filename = ApiClient.convertToType(data['filename'], 'String');
      if (data.hasOwnProperty('file_status'))
        obj.fileStatus = ApiClient.convertToType(data['file_status'], 'String');
      if (data.hasOwnProperty('job_id'))
        obj.jobId = ApiClient.convertToType(data['job_id'], 'String');
    }
    return obj;
  }
}

/**
 * ID of the uploaded video to be used in video_id when creating a document
 * @member {String} videoId
 */
InlineResponse20010.prototype.videoId = undefined;

/**
 * File name of the video
 * @member {String} filename
 */
InlineResponse20010.prototype.filename = undefined;

/**
 * Status of the video
 * @member {String} fileStatus
 */
InlineResponse20010.prototype.fileStatus = undefined;

/**
 * Id of the processing job converting and compressing the video. Poll for job status updates using /video/job/<ID>.
 * @member {String} jobId
 */
InlineResponse20010.prototype.jobId = undefined;

