/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Recipient model module.
 * @module model/Recipient
 * @version 1.6
 */
export class Recipient {
  /**
   * Constructs a new <code>Recipient</code>.
   * Every unique e-mail address (or mobile number) that is connected to a document is a recipient.
   * @alias module:model/Recipient
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Recipient</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Recipient} obj Optional instance to populate.
   * @return {module:model/Recipient} The populated <code>Recipient</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Recipient();
      if (data.hasOwnProperty('thumb_url'))
        obj.thumbUrl = ApiClient.convertToType(data['thumb_url'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('fullname'))
        obj.fullname = ApiClient.convertToType(data['fullname'], 'String');
      if (data.hasOwnProperty('last_name'))
        obj.lastName = ApiClient.convertToType(data['last_name'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('company_name'))
        obj.companyName = ApiClient.convertToType(data['company_name'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('mobile'))
        obj.mobile = ApiClient.convertToType(data['mobile'], 'String');
      if (data.hasOwnProperty('document_url'))
        obj.documentUrl = ApiClient.convertToType(data['document_url'], 'String');
      if (data.hasOwnProperty('first_name'))
        obj.firstName = ApiClient.convertToType(data['first_name'], 'String');
      if (data.hasOwnProperty('company_number'))
        obj.companyNumber = ApiClient.convertToType(data['company_number'], 'String');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('note'))
        obj.note = ApiClient.convertToType(data['note'], 'String');
      if (data.hasOwnProperty('order_num'))
        obj.orderNum = ApiClient.convertToType(data['order_num'], 'String');
      if (data.hasOwnProperty('role'))
        obj.role = ApiClient.convertToType(data['role'], 'String');
      if (data.hasOwnProperty('gender'))
        obj.gender = ApiClient.convertToType(data['gender'], 'String');
    }
    return obj;
  }
}

/**
 * Thumb URL of the recipient
 * @member {String} thumbUrl
 */
Recipient.prototype.thumbUrl = undefined;

/**
 * ID of the recipient
 * @member {String} id
 */
Recipient.prototype.id = undefined;

/**
 * Full name of the recipient
 * @member {String} fullname
 */
Recipient.prototype.fullname = undefined;

/**
 * Last name of the recipient
 * @member {String} lastName
 */
Recipient.prototype.lastName = undefined;

/**
 * Email of the recipient
 * @member {String} email
 */
Recipient.prototype.email = undefined;

/**
 * Company name of the recipient
 * @member {String} companyName
 */
Recipient.prototype.companyName = undefined;

/**
 * Status of the recipient
 * @member {String} status
 */
Recipient.prototype.status = undefined;

/**
 * Mobile number of the recipient
 * @member {String} mobile
 */
Recipient.prototype.mobile = undefined;

/**
 * Unique URL for the recipient to view/sign
 * @member {String} documentUrl
 */
Recipient.prototype.documentUrl = undefined;

/**
 * First name of the recipient
 * @member {String} firstName
 */
Recipient.prototype.firstName = undefined;

/**
 * Company number of the recipient
 * @member {String} companyNumber
 */
Recipient.prototype.companyNumber = undefined;

/**
 * Title of the recipient
 * @member {String} title
 */
Recipient.prototype.title = undefined;

/**
 * Note of the recipient
 * @member {String} note
 */
Recipient.prototype.note = undefined;

/**
 * Signing order of the recipient
 * @member {String} orderNum
 */
Recipient.prototype.orderNum = undefined;

/**
 * @member {String} role
 */
Recipient.prototype.role = undefined;

/**
 * Gender of the recipient
 * @member {String} gender
 */
Recipient.prototype.gender = undefined;

