/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UploadBody1 model module.
 * @module model/UploadBody1
 * @version 1.6
 */
export class UploadBody1 {
  /**
   * Constructs a new <code>UploadBody1</code>.
   * @alias module:model/UploadBody1
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UploadBody1</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UploadBody1} obj Optional instance to populate.
   * @return {module:model/UploadBody1} The populated <code>UploadBody1</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UploadBody1();
      if (data.hasOwnProperty('file'))
        obj.file = ApiClient.convertToType(data['file'], 'Blob');
    }
    return obj;
  }
}

/**
 * Binary File
 * @member {Blob} file
 */
UploadBody1.prototype.file = undefined;

