/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UsersUsers model module.
 * @module model/UsersUsers
 * @version 1.6
 */
export class UsersUsers {
  /**
   * Constructs a new <code>UsersUsers</code>.
   * @alias module:model/UsersUsers
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UsersUsers</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UsersUsers} obj Optional instance to populate.
   * @return {module:model/UsersUsers} The populated <code>UsersUsers</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UsersUsers();
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('first_name'))
        obj.firstName = ApiClient.convertToType(data['first_name'], 'String');
      if (data.hasOwnProperty('last_name'))
        obj.lastName = ApiClient.convertToType(data['last_name'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('role'))
        obj.role = ApiClient.convertToType(data['role'], 'String');
      if (data.hasOwnProperty('team_name'))
        obj.teamName = ApiClient.convertToType(data['team_name'], 'String');
      if (data.hasOwnProperty('last_login'))
        obj.lastLogin = ApiClient.convertToType(data['last_login'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} userId
 */
UsersUsers.prototype.userId = undefined;

/**
 * @member {String} name
 */
UsersUsers.prototype.name = undefined;

/**
 * @member {String} firstName
 */
UsersUsers.prototype.firstName = undefined;

/**
 * @member {String} lastName
 */
UsersUsers.prototype.lastName = undefined;

/**
 * @member {String} email
 */
UsersUsers.prototype.email = undefined;

/**
 * @member {String} status
 */
UsersUsers.prototype.status = undefined;

/**
 * @member {String} role
 */
UsersUsers.prototype.role = undefined;

/**
 * @member {String} teamName
 */
UsersUsers.prototype.teamName = undefined;

/**
 * @member {String} lastLogin
 */
UsersUsers.prototype.lastLogin = undefined;

