/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {UsersUsers} from './UsersUsers';

/**
 * The Users model module.
 * @module model/Users
 * @version 1.6
 */
export class Users {
  /**
   * Constructs a new <code>Users</code>.
   * User list
   * @alias module:model/Users
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Users</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Users} obj Optional instance to populate.
   * @return {module:model/Users} The populated <code>Users</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Users();
      if (data.hasOwnProperty('users'))
        obj.users = ApiClient.convertToType(data['users'], [UsersUsers]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/UsersUsers>} users
 */
Users.prototype.users = undefined;

