/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Document} from './Document';
import {Recipient} from './Recipient';
import {WebhookEntity} from './WebhookEntity';

/**
 * The Webhook model module.
 * @module model/Webhook
 * @version 1.6
 */
export class Webhook {
  /**
   * Constructs a new <code>Webhook</code>.
   * Webhook payload
   * @alias module:model/Webhook
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Webhook</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Webhook} obj Optional instance to populate.
   * @return {module:model/Webhook} The populated <code>Webhook</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Webhook();
      if (data.hasOwnProperty('event_action'))
        obj.eventAction = ApiClient.convertToType(data['event_action'], 'String');
      if (data.hasOwnProperty('subscription_id'))
        obj.subscriptionId = ApiClient.convertToType(data['subscription_id'], 'String');
      if (data.hasOwnProperty('document'))
        obj.document = Document.constructFromObject(data['document']);
      if (data.hasOwnProperty('entity'))
        obj.entity = WebhookEntity.constructFromObject(data['entity']);
      if (data.hasOwnProperty('recipient'))
        obj.recipient = Recipient.constructFromObject(data['recipient']);
      if (data.hasOwnProperty('custom_fields'))
        obj.customFields = ApiClient.convertToType(data['custom_fields'], {'String': 'String'});
      if (data.hasOwnProperty('event'))
        obj.event = ApiClient.convertToType(data['event'], 'String');
      if (data.hasOwnProperty('event_type'))
        obj.eventType = ApiClient.convertToType(data['event_type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} eventAction
 */
Webhook.prototype.eventAction = undefined;

/**
 * @member {String} subscriptionId
 */
Webhook.prototype.subscriptionId = undefined;

/**
 * @member {module:model/Document} document
 */
Webhook.prototype.document = undefined;

/**
 * @member {module:model/WebhookEntity} entity
 */
Webhook.prototype.entity = undefined;

/**
 * @member {module:model/Recipient} recipient
 */
Webhook.prototype.recipient = undefined;

/**
 * @member {Object.<String, String>} customFields
 */
Webhook.prototype.customFields = undefined;

/**
 * @member {String} event
 */
Webhook.prototype.event = undefined;

/**
 * @member {String} eventType
 */
Webhook.prototype.eventType = undefined;

