/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The WebhookEntity model module.
 * @module model/WebhookEntity
 * @version 1.6
 */
export class WebhookEntity {
  /**
   * Constructs a new <code>WebhookEntity</code>.
   * Entity for the webhook
   * @alias module:model/WebhookEntity
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>WebhookEntity</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WebhookEntity} obj Optional instance to populate.
   * @return {module:model/WebhookEntity} The populated <code>WebhookEntity</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new WebhookEntity();
      if (data.hasOwnProperty('email_send_message'))
        obj.emailSendMessage = ApiClient.convertToType(data['email_send_message'], 'String');
      if (data.hasOwnProperty('sub_domain'))
        obj.subDomain = ApiClient.convertToType(data['sub_domain'], 'String');
      if (data.hasOwnProperty('custom_domain'))
        obj.customDomain = ApiClient.convertToType(data['custom_domain'], 'String');
      if (data.hasOwnProperty('email_send_subject'))
        obj.emailSendSubject = ApiClient.convertToType(data['email_send_subject'], 'String');
    }
    return obj;
  }
}

/**
 * Default email message
 * @member {String} emailSendMessage
 */
WebhookEntity.prototype.emailSendMessage = undefined;

/**
 * Sub-domain for the entity
 * @member {String} subDomain
 */
WebhookEntity.prototype.subDomain = undefined;

/**
 * Custom domain setting for entity
 * @member {String} customDomain
 */
WebhookEntity.prototype.customDomain = undefined;

/**
 * Default email subject
 * @member {String} emailSendSubject
 */
WebhookEntity.prototype.emailSendSubject = undefined;

