/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {Error} from '../model/Error';
import {EventsRejectedBody} from '../model/EventsRejectedBody';
import {EventsReviewedBody} from '../model/EventsReviewedBody';
import {EventsSignedBody} from '../model/EventsSignedBody';
import {Subscription} from '../model/Subscription';

/**
* Others service.
* @module api/OthersApi
* @version 1.6
*/
export class OthersApi {

    /**
    * Constructs a new OthersApi. 
    * @alias module:api/OthersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the createRejectedSubscription operation.
     * @callback moduleapi/OthersApi~createRejectedSubscriptionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Subscription{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * When a document has been rejected
     * Triggers when a document has been rejected by any of the recipients
     * @param {module:model/EventsRejectedBody} body A JSON object containing subscription information
     * @param {module:api/OthersApi~createRejectedSubscriptionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    createRejectedSubscription(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createRejectedSubscription");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Oauth2', 'Token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Subscription;

      return this.apiClient.callApi(
        '/subscriptions/events/rejected', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the createReviewedSubscription operation.
     * @callback moduleapi/OthersApi~createReviewedSubscriptionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Subscription{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * When a document has been reviewed
     * Triggers when a document has been reviewed by any of the recipients
     * @param {module:model/EventsReviewedBody} body A JSON object containing subscription information
     * @param {module:api/OthersApi~createReviewedSubscriptionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    createReviewedSubscription(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createReviewedSubscription");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Oauth2', 'Token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Subscription;

      return this.apiClient.callApi(
        '/subscriptions/events/reviewed', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the createSignedSubscription operation.
     * @callback moduleapi/OthersApi~createSignedSubscriptionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Subscription{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * When a document has been signed
     * Triggers when a document has been signed by all signing parties
     * @param {module:model/EventsSignedBody} body A JSON object containing subscription information
     * @param {module:api/OthersApi~createSignedSubscriptionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    createSignedSubscription(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createSignedSubscription");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['Oauth2', 'Token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Subscription;

      return this.apiClient.callApi(
        '/subscriptions/events/signed', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}