/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GetAccept);
  }
}(this, function(expect, GetAccept) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse20011Attachments', function() {
      beforeEach(function() {
        instance = new GetAccept.InlineResponse20011Attachments();
      });

      it('should create an instance of InlineResponse20011Attachments', function() {
        // TODO: update the code to test InlineResponse20011Attachments
        expect(instance).to.be.a(GetAccept.InlineResponse20011Attachments);
      });

      it('should have the property attachmentId (base name: "attachment_id")', function() {
        // TODO: update the code to test the property attachmentId
        expect(instance).to.have.property('attachmentId');
        // expect(instance.attachmentId).to.be(expectedValueLiteral);
      });

      it('should have the property attachmentType (base name: "attachment_type")', function() {
        // TODO: update the code to test the property attachmentType
        expect(instance).to.have.property('attachmentType');
        // expect(instance.attachmentType).to.be(expectedValueLiteral);
      });

      it('should have the property attachmentTitle (base name: "attachment_title")', function() {
        // TODO: update the code to test the property attachmentTitle
        expect(instance).to.have.property('attachmentTitle');
        // expect(instance.attachmentTitle).to.be(expectedValueLiteral);
      });

      it('should have the property attachmentUrl (base name: "attachment_url")', function() {
        // TODO: update the code to test the property attachmentUrl
        expect(instance).to.have.property('attachmentUrl');
        // expect(instance.attachmentUrl).to.be(expectedValueLiteral);
      });

      it('should have the property published (base name: "published")', function() {
        // TODO: update the code to test the property published
        expect(instance).to.have.property('published');
        // expect(instance.published).to.be(expectedValueLiteral);
      });

      it('should have the property library (base name: "library")', function() {
        // TODO: update the code to test the property library
        expect(instance).to.have.property('library');
        // expect(instance.library).to.be(expectedValueLiteral);
      });

    });
  });

}));
