/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GetAccept);
  }
}(this, function(expect, GetAccept) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse2003Videos', function() {
      beforeEach(function() {
        instance = new GetAccept.InlineResponse2003Videos();
      });

      it('should create an instance of InlineResponse2003Videos', function() {
        // TODO: update the code to test InlineResponse2003Videos
        expect(instance).to.be.a(GetAccept.InlineResponse2003Videos);
      });

      it('should have the property videoId (base name: "video_id")', function() {
        // TODO: update the code to test the property videoId
        expect(instance).to.have.property('videoId');
        // expect(instance.videoId).to.be(expectedValueLiteral);
      });

      it('should have the property videoType (base name: "video_type")', function() {
        // TODO: update the code to test the property videoType
        expect(instance).to.have.property('videoType');
        // expect(instance.videoType).to.be(expectedValueLiteral);
      });

      it('should have the property videoTitle (base name: "video_title")', function() {
        // TODO: update the code to test the property videoTitle
        expect(instance).to.have.property('videoTitle');
        // expect(instance.videoTitle).to.be(expectedValueLiteral);
      });

      it('should have the property videoUrl (base name: "video_url")', function() {
        // TODO: update the code to test the property videoUrl
        expect(instance).to.have.property('videoUrl');
        // expect(instance.videoUrl).to.be(expectedValueLiteral);
      });

      it('should have the property thumbUrl (base name: "thumb_url")', function() {
        // TODO: update the code to test the property thumbUrl
        expect(instance).to.have.property('thumbUrl');
        // expect(instance.thumbUrl).to.be(expectedValueLiteral);
      });

      it('should have the property saved (base name: "saved")', function() {
        // TODO: update the code to test the property saved
        expect(instance).to.have.property('saved');
        // expect(instance.saved).to.be(expectedValueLiteral);
      });

      it('should have the property published (base name: "published")', function() {
        // TODO: update the code to test the property published
        expect(instance).to.have.property('published');
        // expect(instance.published).to.be(expectedValueLiteral);
      });

      it('should have the property editable (base name: "editable")', function() {
        // TODO: update the code to test the property editable
        expect(instance).to.have.property('editable');
        // expect(instance.editable).to.be(expectedValueLiteral);
      });

    });
  });

}));
