/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GetAccept);
  }
}(this, function(expect, GetAccept) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SubscriptionsBody', function() {
      beforeEach(function() {
        instance = new GetAccept.SubscriptionsBody();
      });

      it('should create an instance of SubscriptionsBody', function() {
        // TODO: update the code to test SubscriptionsBody
        expect(instance).to.be.a(GetAccept.SubscriptionsBody);
      });

      it('should have the property event (base name: "event")', function() {
        // TODO: update the code to test the property event
        expect(instance).to.have.property('event');
        // expect(instance.event).to.be(expectedValueLiteral);
      });

      it('should have the property targetUrl (base name: "target_url")', function() {
        // TODO: update the code to test the property targetUrl
        expect(instance).to.have.property('targetUrl');
        // expect(instance.targetUrl).to.be(expectedValueLiteral);
      });

      it('should have the property host (base name: "host")', function() {
        // TODO: update the code to test the property host
        expect(instance).to.have.property('host');
        // expect(instance.host).to.be(expectedValueLiteral);
      });

      it('should have the property payload (base name: "payload")', function() {
        // TODO: update the code to test the property payload
        expect(instance).to.have.property('payload');
        // expect(instance.payload).to.be(expectedValueLiteral);
      });

      it('should have the property global (base name: "global")', function() {
        // TODO: update the code to test the property global
        expect(instance).to.have.property('global');
        // expect(instance.global).to.be(expectedValueLiteral);
      });

      it('should have the property notificationEmail (base name: "notification_email")', function() {
        // TODO: update the code to test the property notificationEmail
        expect(instance).to.have.property('notificationEmail');
        // expect(instance.notificationEmail).to.be(expectedValueLiteral);
      });

    });
  });

}));
