/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GetAccept);
  }
}(this, function(expect, GetAccept) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('WebhookEntity', function() {
      beforeEach(function() {
        instance = new GetAccept.WebhookEntity();
      });

      it('should create an instance of WebhookEntity', function() {
        // TODO: update the code to test WebhookEntity
        expect(instance).to.be.a(GetAccept.WebhookEntity);
      });

      it('should have the property emailSendMessage (base name: "email_send_message")', function() {
        // TODO: update the code to test the property emailSendMessage
        expect(instance).to.have.property('emailSendMessage');
        // expect(instance.emailSendMessage).to.be(expectedValueLiteral);
      });

      it('should have the property subDomain (base name: "sub_domain")', function() {
        // TODO: update the code to test the property subDomain
        expect(instance).to.have.property('subDomain');
        // expect(instance.subDomain).to.be(expectedValueLiteral);
      });

      it('should have the property customDomain (base name: "custom_domain")', function() {
        // TODO: update the code to test the property customDomain
        expect(instance).to.have.property('customDomain');
        // expect(instance.customDomain).to.be(expectedValueLiteral);
      });

      it('should have the property emailSendSubject (base name: "email_send_subject")', function() {
        // TODO: update the code to test the property emailSendSubject
        expect(instance).to.have.property('emailSendSubject');
        // expect(instance.emailSendSubject).to.be(expectedValueLiteral);
      });

    });
  });

}));
