/*
 * GetAccept
 * GetAccept provides a sales enablement platform for sales to design, send, promote, track, and e-sign sales documents, leveraging sales collateral, contract management, proposals, and electronic signatures in one place.
 *
 * OpenAPI spec version: 1.6
 * Contact: integrations@getaccept.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GetAccept);
  }
}(this, function(expect, GetAccept) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GetAccept.DocumentsApi();
  });

  describe('(package)', function() {
    describe('DocumentsApi', function() {
      describe('createDocument', function() {
        it('should call createDocument successfully', function(done) {
          // TODO: uncomment, update parameter values for createDocument call and complete the assertions
          /*

          instance.createDocument(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GetAccept.Document);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('downloadDocument', function() {
        it('should call downloadDocument successfully', function(done) {
          // TODO: uncomment, update parameter values for downloadDocument call and complete the assertions
          /*
          var opts = {};

          instance.downloadDocument(documentId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GetAccept.InlineResponse2004);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getDocumentDetails', function() {
        it('should call getDocumentDetails successfully', function(done) {
          // TODO: uncomment, update parameter values for getDocumentDetails call and complete the assertions
          /*

          instance.getDocumentDetails(documentId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GetAccept.Document);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listDocumentFields', function() {
        it('should call listDocumentFields successfully', function(done) {
          // TODO: uncomment, update parameter values for listDocumentFields call and complete the assertions
          /*

          instance.listDocumentFields(documentId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GetAccept.Fields);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listDocuments', function() {
        it('should call listDocuments successfully', function(done) {
          // TODO: uncomment, update parameter values for listDocuments call and complete the assertions
          /*
          var opts = {};

          instance.listDocuments(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GetAccept.Documents);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listRecipients', function() {
        it('should call listRecipients successfully', function(done) {
          // TODO: uncomment, update parameter values for listRecipients call and complete the assertions
          /*

          instance.listRecipients(documentId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GetAccept.Recipients);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('sealDocument', function() {
        it('should call sealDocument successfully', function(done) {
          // TODO: uncomment, update parameter values for sealDocument call and complete the assertions
          /*
          var opts = {};

          instance.sealDocument(documentId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GetAccept.Recipients);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('sendDocument', function() {
        it('should call sendDocument successfully', function(done) {
          // TODO: uncomment, update parameter values for sendDocument call and complete the assertions
          /*
          var opts = {};

          instance.sendDocument(documentId, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GetAccept.Document);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('uploadDocument', function() {
        it('should call uploadDocument successfully', function(done) {
          // TODO: uncomment, update parameter values for uploadDocument call and complete the assertions
          /*

          instance.uploadDocument(body, file, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(GetAccept.InlineResponse2008);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
